-- 휴가 유형 추가(2026-10-07 QA #30, 본부 답변 #19). prisma/schema.prisma 의 enum LeaveType 과 1:1.
-- 운영에는 prisma db push 를 쓰지 않는다 — 배포 전에 넣는다. ADD VALUE 는 되돌릴 수 없지만 다시 돌려도 안전하다(IF NOT EXISTS).
-- ⚠ BEGIN/COMMIT 없이 한 줄씩 — 새 값은 같은 트랜잭션 안에서 쓸 수 없다.
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'COMP_LEAVE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'COMP_LEAVE_HALF';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'PRENATAL_CHECKUP';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'REWARD';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'MATERNITY';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'SPOUSE_BIRTH';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'FAMILY_CARE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'OTHER_PAID';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'OTHER_UNPAID';
